name: Test Builds

on: push

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        go-version: [1.13x, 1.14.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: make install
      # - name: Lint
      #   run: make lint
      - name: test
        run: make test
