name: Test Builds

on: push

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: make install
      - name: Lint
        run: make lint
      - name: test
        run: make test

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: make install
      - name: Lint
        run: make lint
      - name: test
        run: make test

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: make install
      - name: Lint
        run: make lint
      - name: test
        run: make test
